twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        wscsite: '@App\Templating\GlobalVariable'
        lazy_loading: '%env(bool:IMAGE_LAZY_LOADING)%'
